# Generated by Django 3.2 on 2021-04-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210421_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='elapsed_time',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
