# Generated by Django 3.2 on 2021-04-21 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210421_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
