# Generated by Django 3.2 on 2021-04-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersession_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
