# Generated by Django 3.2 on 2021-04-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
